spring:
  application:
    name: webfl
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id:
      ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

app:
  myport: ${PORT:0}

server:
  port: ${app.myport}
